export { cn } from './utils/cn'

export { usePrefersReducedMotion } from './hooks/usePrefersReducedMotion'

/* Primitives — translucent media UI */
export { GlassCard, glassCardVariants } from './primitives/GlassCard'
export type { GlassCardProps } from './primitives/GlassCard'
export { StickyRail } from './primitives/StickyRail'
export type { StickyRailProps } from './primitives/StickyRail'
export { Ticker } from './primitives/Ticker'
export type { TickerProps } from './primitives/Ticker'
export { AnnouncementBar } from './primitives/AnnouncementBar'
export type { AnnouncementBarProps } from './primitives/AnnouncementBar'
export { AdSlotFrame } from './primitives/AdSlotFrame'
export type { AdSlotFrameProps } from './primitives/AdSlotFrame'
export { AdSlotEmptyState } from './molecules/AdSlotEmptyState'
export type { AdSlotEmptyStateProps } from './molecules/AdSlotEmptyState'
export { AdCreativeDisplay } from './molecules/AdCreativeDisplay'
export type {
  AdCreativeDisplayProps,
  AdCreativeDisplayModel,
  AdCreativeFormat,
} from './molecules/AdCreativeDisplay'
export { MotionEnter } from './primitives/MotionEnter'
export type { MotionEnterProps } from './primitives/MotionEnter'
export { SubtleParallax } from './primitives/SubtleParallax'
export type { SubtleParallaxProps } from './primitives/SubtleParallax'

/* Atoms */
export { Button, buttonVariants } from './atoms/Button'
export { Dot } from './atoms/Dot'
export { Text, textVariants } from './atoms/Text'
export { Heading, headingVariants } from './atoms/Heading'
export { Badge, badgeVariants } from './atoms/Badge'
export { Link, linkVariants } from './atoms/Link'
export { Separator } from './atoms/Separator'
export { Label, labelVariants } from './atoms/Label'
export { Timestamp } from './atoms/Timestamp'
export { AuthorName } from './atoms/AuthorName'
export { Source } from './atoms/Source'
export { Input } from './atoms/Input'
export { SearchInput, searchInputVariants } from './atoms/SearchInput'
export { Checkbox } from './atoms/Checkbox'
export { Radio } from './atoms/Radio'
export { Toggle } from './atoms/Toggle'
export { Select } from './atoms/Select'
export type { SelectOption } from './atoms/Select'
export { Slider } from './atoms/Slider'
export { Textarea } from './atoms/Textarea'
export { Thumbnail } from './atoms/Thumbnail'
export { Avatar } from './atoms/Avatar'
export { Logo } from './atoms/Logo'

/* Molecules */
export { SectionHeader } from './molecules/SectionHeader'
export { Card, CardHeader, CardContent, CardFooter, cardVariants } from './molecules/Card'
export { GlitchText } from './molecules/GlitchText'
export { MarqueeBand } from './molecules/MarqueeBand'
export { ThemeToggle } from './molecules/ThemeToggle'
export { Blockquote, BlockquoteContent, BlockquoteFooter } from './molecules/Blockquote'
export { FillHoverAnchor } from './molecules/FillHoverAnchor'
export { NavLinksList } from './molecules/NavLinksList'
export type { NavLinkItem } from './molecules/NavLinksList'
export { BackLink } from './molecules/BackLink'
export { Tabs, TabsList, TabsTrigger, TabsContent } from './molecules/Tabs'
export { Breadcrumb } from './molecules/Breadcrumb'
export type { BreadcrumbItem } from './molecules/Breadcrumb'
export { CategoryChips } from './molecules/CategoryChips'
export type { CategoryChipItem } from './molecules/CategoryChips'
export { AuthorBlock } from './molecules/AuthorBlock'
export { MetaBar } from './molecules/MetaBar'
export { Loader } from './molecules/Loader'
export { Skeleton, skeletonVariants } from './molecules/Skeleton'
export type { SkeletonProps } from './molecules/Skeleton'
export { Alert, alertVariants } from './molecules/Alert'
export { Dialog } from './molecules/Dialog'
export type { DialogProps } from './molecules/Dialog'
export { PromptDialog } from './molecules/PromptDialog'
export type { PromptDialogProps } from './molecules/PromptDialog'
export { AlertDialog } from './molecules/AlertDialog'
export type { AlertDialogProps } from './molecules/AlertDialog'
export { ConfirmDialog } from './molecules/ConfirmDialog'
export type { ConfirmDialogProps } from './molecules/ConfirmDialog'
export { Tooltip } from './molecules/Tooltip'
export { DatePicker } from './molecules/DatePicker'
export type { DatePickerProps } from './molecules/DatePicker'
export { StatusBadge } from './molecules/StatusBadge'
export type { StatusBadgeProps } from './molecules/StatusBadge'
export { LockBanner } from './molecules/LockBanner'
export type { LockBannerProps } from './molecules/LockBanner'
export { DraftRestoredBanner } from './molecules/DraftRestoredBanner'
export type { DraftRestoredBannerProps } from './molecules/DraftRestoredBanner'
export { SaveIndicator } from './molecules/SaveIndicator'
export type { SaveState, SaveIndicatorProps } from './molecules/SaveIndicator'
export { RevisionItem } from './molecules/RevisionItem'
export type { RevisionItemProps } from './molecules/RevisionItem'
export { EditorialComment } from './molecules/EditorialComment'
export type { EditorialCommentProps } from './molecules/EditorialComment'
export { EditorialSearchForm } from './molecules/EditorialSearchForm'
export type { EditorialSearchFormProps } from './molecules/EditorialSearchForm'
export { CtaLink } from './molecules/CtaLink'
export type { CtaLinkProps, CtaLinkLinkComponent } from './molecules/CtaLink'
export { AdminTable } from './molecules/AdminTable'
export type { AdminTableProps } from './molecules/AdminTable'
export { AdminFormSection } from './molecules/AdminFormSection'
export type { AdminFormSectionProps } from './molecules/AdminFormSection'
export { EditorialFilterTabs } from './molecules/EditorialFilterTabs'
export type { EditorialFilterTabsProps, EditorialFilterTab } from './molecules/EditorialFilterTabs'
export { ContributionCard } from './molecules/ContributionCard'
export type { ContributionCardProps } from './molecules/ContributionCard'
export { EditorialStickyPanel } from './molecules/EditorialStickyPanel'
export type { EditorialStickyPanelProps } from './molecules/EditorialStickyPanel'
export { SegmentedToggle } from './molecules/SegmentedToggle'
export type { SegmentedToggleProps, SegmentedToggleOption } from './molecules/SegmentedToggle'
export { EditorialAccountGate } from './molecules/EditorialAccountGate'
export type { EditorialAccountGateProps } from './molecules/EditorialAccountGate'
export { MediaFeatureCard } from './molecules/MediaFeatureCard'
export type { MediaFeatureCardProps } from './molecules/MediaFeatureCard'

export { ThemeProvider } from './providers/ThemeProvider'

/* Patterns */
export { AfricanPattern } from './patterns/AfricanPattern'

/* Organisms */
export { CursorTracker } from './organisms/CursorTracker'
export { Header } from './organisms/Header'
export { Footer } from './organisms/Footer'
export type { FooterLink } from './organisms/Footer'
export { EditorialSearchHero } from './organisms/EditorialSearchHero'
export type { EditorialSearchHeroProps } from './organisms/EditorialSearchHero'
export { EditorialReaderHeader } from './organisms/EditorialReaderHeader'
export type {
  EditorialReaderHeaderProps,
  EditorialReaderHeaderLinkProps,
} from './organisms/EditorialReaderHeader'
export { BrandsMarketingHeader } from './organisms/BrandsMarketingHeader'
export type { BrandsMarketingHeaderProps, BrandsHeaderLinkProps } from './organisms/BrandsMarketingHeader'
export { EditorialSignalHero } from './organisms/EditorialSignalHero'
export type { EditorialSignalHeroProps } from './organisms/EditorialSignalHero'

export { toYoutubeEmbedUrl, isValidYoutubeUrl } from './utils/youtubeEmbed'
